FROM panther.centraldg6.athens.intrasoft-intl.private:32443/ermis-tn-external-libs/oracle-db:12.2.0.1-slim

WORKDIR /home/oracle/setup/custom_scripts

COPY src/main/resources/liquibase/com.poc.chat.application/configDBora.sh /home/oracle/setup/
